# FTSE 100 Stock Tracker — Returns & Risk Analysis

## Objective

This notebook transforms the raw price data into performance metrics.

Using the adjusted closing prices collected in Notebook 01, we calculate:

- Total Returns
- Volatility (Risk)

These metrics form the foundation of the ranking model developed in Notebook 03.

## Method

We compute:

- Cumulative return for each stock over the selected time period
- Annualised volatility as a measure of price risk

These outputs allow us to compare performance consistency across FTSE 100 constituents before applying a ranking framework.

In [1]:
import pandas as pd
import numpy as np

prices = pd.read_csv("../data/raw/ftse100_prices.csv")
prices.head()

,date,AAF.L,AAL.L,ABF.L,ADM.L,AHT.L,ALW.L,ANTO.L,AUTO.L,AV.L,...,SVT.L,TSCO.L,TW.L,ULVR.L,UTG.L,UU.L,VOD.L,WEIR.L,WPP.L,WTB.L
0,2023-01-03,114.172134,3201.505859,1625.443726,2159.630371,4797.553711,952.350952,1561.053955,520.158630,447.936859,...,2670.474121,228.739777,104.409355,4479.897949,923.395752,1004.125061,85.712036,1658.080566,833.269470,2673.580566
1,2023-01-04,118.567207,3116.250000,1670.900146,2219.536865,4907.497559,965.341980,1553.058716,525.156189,455.819916,...,2767.346191,234.732971,107.751648,4515.685059,938.377930,1037.579346,87.607651,1665.076660,853.037842,2699.556641
2,2023-01-05,117.768120,3252.463623,1742.831421,2199.568359,4914.494141,966.341370,1609.524414,534.180481,447.737305,...,2745.375244,238.228973,107.901306,4487.908203,921.897583,1028.092407,88.565437,1660.079102,855.833496,2755.506348
3,2023-01-06,118.167664,3438.654541,1769.305908,2220.535645,5015.442383,970.338745,1653.997559,539.578247,455.021637,...,2788.318848,241.125687,108.599701,4488.442383,929.388611,1046.566895,88.505577,1691.561768,861.823975,2799.466309
4,2023-01-09,114.371918,3509.700928,1748.326172,2204.560303,5107.395996,975.335266,1725.454224,546.975281,454.023773,...,2734.390137,242.923630,106.654167,4481.498047,938.377930,1025.595825,88.485634,1709.052124,883.988464,2805.460693

In [2]:
prices["date"] = pd.to_datetime(prices["date"])
prices = prices.set_index("date")
prices.head()

,AAF.L,AAL.L,ABF.L,ADM.L,AHT.L,ALW.L,ANTO.L,AUTO.L,AV.L,AZN.L,...,SVT.L,TSCO.L,TW.L,ULVR.L,UTG.L,UU.L,VOD.L,WEIR.L,WPP.L,WTB.L
date,,,,,,,,,,,,,,,,,,,,,
2023-01-03,114.172134,3201.505859,1625.443726,2159.630371,4797.553711,952.350952,1561.053955,520.158630,447.936859,11526.686523,...,2670.474121,228.739777,104.409355,4479.897949,923.395752,1004.125061,85.712036,1658.080566,833.269470,2673.580566
2023-01-04,118.567207,3116.250000,1670.900146,2219.536865,4907.497559,965.341980,1553.058716,525.156189,455.819916,11594.643555,...,2767.346191,234.732971,107.751648,4515.685059,938.377930,1037.579346,87.607651,1665.076660,853.037842,2699.556641
2023-01-05,117.768120,3252.463623,1742.831421,2199.568359,4914.494141,966.341370,1609.524414,534.180481,447.737305,11702.575195,...,2745.375244,238.228973,107.901306,4487.908203,921.897583,1028.092407,88.565437,1660.079102,855.833496,2755.506348
2023-01-06,118.167664,3438.654541,1769.305908,2220.535645,5015.442383,970.338745,1653.997559,539.578247,455.021637,11774.528320,...,2788.318848,241.125687,108.599701,4488.442383,929.388611,1046.566895,88.505577,1691.561768,861.823975,2799.466309
2023-01-09,114.371918,3509.700928,1748.326172,2204.560303,5107.395996,975.335266,1725.454224,546.975281,454.023773,11728.557617,...,2734.390137,242.923630,106.654167,4481.498047,938.377930,1025.595825,88.485634,1709.052124,883.988464,2805.460693

In [3]:
returns = prices.pct_change()
returns.head()

,AAF.L,AAL.L,ABF.L,ADM.L,AHT.L,ALW.L,ANTO.L,AUTO.L,AV.L,AZN.L,...,SVT.L,TSCO.L,TW.L,ULVR.L,UTG.L,UU.L,VOD.L,WEIR.L,WPP.L,WTB.L
date,,,,,,,,,,,,,,,,,,,,,
2023-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-04,0.038495,-0.026630,0.027966,0.027739,0.022917,0.013641,-0.005122,0.009608,0.017599,0.005896,...,0.036275,0.026201,0.032011,0.007988,0.016225,0.033317,0.022116,0.004219,0.023724,0.009716
2023-01-05,-0.006740,0.043711,0.043049,-0.008997,0.001426,0.001035,0.036358,0.017184,-0.017732,0.009309,...,-0.007939,0.014894,0.001389,-0.006151,-0.017563,-0.009143,0.010933,-0.003001,0.003277,0.020726
2023-01-06,0.003393,0.057246,0.015191,0.009532,0.020541,0.004137,0.027631,0.010105,0.016269,0.006148,...,0.015642,0.012159,0.006473,0.000119,0.008126,0.017970,-0.000676,0.018965,0.007000,0.015953
2023-01-09,-0.032122,0.020661,-0.011858,-0.007194,0.018334,0.005149,0.043202,0.013709,-0.002193,-0.003904,...,-0.019341,0.007456,-0.017915,-0.001547,0.009672,-0.020038,-0.000225,0.010340,0.025718,0.002141

In [4]:
total_return = (prices.iloc[-1] / prices.iloc[0]) - 1
total_return.head()

AAF.L    2.142623
AAL.L    0.128531
ABF.L    0.214130
ADM.L    0.329857
AHT.L    0.058456
dtype: float64

In [5]:
volatility = returns.std() * np.sqrt(252)
volatility.head()

AAF.L    0.305986
AAL.L    0.382844
ABF.L    0.242338
ADM.L    0.226855
AHT.L    0.305508
dtype: float64

In [6]:
metrics = pd.DataFrame({
    "total_return": total_return,
    "volatility": volatility
})

metrics = metrics.dropna()
metrics.head()

       total_return  volatility
AAF.L      2.142623    0.305986
AAL.L      0.128531    0.382844
ABF.L      0.214130    0.242338
ADM.L      0.329857    0.226855
AHT.L      0.058456    0.305508

In [7]:
metrics.to_csv("../data/processed/ftse100_metrics.csv")

## Summary of Findings

We have successfully transformed raw price data into two key performance metrics:

- Total return, measuring overall price growth
- Volatility, serving as a proxy for risk

These return and risk metrics now provide the foundation for a structured ranking model.

In the next notebook, we combine these measures into a composite score to identify stocks offering the strongest risk-adjusted performance and analyse sector patterns within the FTSE 100.